### PR TITLE
Use standards

### PR DESCRIPTION
**Pull request by karissademi**
# Use the Standards!
* Removes references to the pattern portfolio and updates layout to fall in line with single page applications.

### CODE REVIEW

**Comment by timwis** [comment]
Looks great, and love the hero image. The only thing I'm worried about is including the dependency as part of the source control of this particular project :-/ If we're pulling it in via npm, I guess the _ideal_ approach would be to have a build script run and deploy to gh-pages...but that also seems a bit much for a simple site. Perhaps we should brainstorm about this a bit tomorrow.

**Comment by karissademi** [comment]
Sure, we can discuss. I purposefully chose to include the dependency in the source control because this project is so simple and doesn't have a build process currently in place. Another option is to point directly to the latest version of the standards compiled files through `https://cityofphiladelphia.github.io/standards-docs/css/standards.css` (eventually standards.phila.gov).

**Comment by gsf** [comment]
Hi! Are there URLs for each version of standards.css? Seems like that would be useful for simple apps that don't get updated as often.

**Comment by karissademi** [comment]
@gsf I moved away from individual URLs for each release of Standards, in part because Patterns started to look like [this](https://github.com/CityOfPhiladelphia/patterns/tree/gh-pages/dist). 

Ideally, these smaller sites would adopt a build process, eliminating the need to include the compiled files. I don't think we're there yet, though. That's why the option to download the `/dist` files directly exists at all.

**Comment by gsf** [comment]
Gotcha. The option to src specific release files is a nice to have, but vendoring it in is actually more robust.

**Comment by karissademi** [comment]
I just discovered https://unpkg.com/ which looks like it will make @timwis happy and solve the issue of cluttering up the repo.

**Comment by karissademi** [comment]
Instead of vendoring, I used unpkg links for the assets. 

This now also updates the footer and related content links.

**Pull request merged**
